"""Fewster-Ford-Roman (2012) moment method, transcribed and run on our kernel.

C. J. Fewster, L. H. Ford and T. A. Roman, "Probability distributions for
quantum stress tensors in four dimensions", Phys. Rev. D 85, 125038 (2012)
[arXiv:1204.3570], compute the vacuum moments of the Lorentzian-smeared Wick
squares :phi^2: (p = 1) and :phidot^2: (p = 3) of the 4d massless scalar,
and estimate the lower edge of the probability distribution -- which, by their
Sec. II argument, is the optimal quantum-inequality bound x0 -- by a Stieltjes
moment test. This module reproduces every step of that pipeline so that it can
be run on demand next to our direct minimization of the same operator.

Their conventions (transcribed)
-------------------------------
* Sampling function f(t) = tau / (pi (t^2 + tau^2)), Eq. (9); dimensionless
  moments a_n = (4 pi tau)^{2n} mu_n for phi^2 (Eq. 19) and
  a_n = (4 pi tau^2)^{2n} mu_n for phidot^2 (Eq. 20); mu_n = <T^n>_vac with
  T = int f :phi^2: dt, Eq. (12).
* Appendix A (Fourier-space rules). Two-point function
  <phi(t) phi(t')> = (4 pi^2)^{-1} int_0^inf dw w^p e^{-i w (t - t' - i eps)}
  (A1); a connected n-vertex graph is a permutation with "runs"; for the
  Lorentzian, fhat(w) = e^{-|w| tau} makes every double-source / double-target
  vertex factorize, so each graph is a product over its runs of the chain
  integrals (A3)

      K_n^{(r)} = (2^r/r!) int_{R+^n} dk_1..dk_n k_1^{p+r} (k_2..k_n)^p
                  e^{-k_1} e^{-sum_i |k_{i+1} - k_i|} e^{-k_n},

  evaluated exactly by the recurrence (A6)
      K_n^{(r)} = (p!/2^{p+1}) C(p+r, p) sum_{r'=0}^{p+r+1} K_{n-1}^{(r')},
      K_1^{(r)} = 2^{-(p+1)} p! C(p+r, p),
  and the sum over graphs is generated by the run-structure polynomials (A8)
      script-K_n = sum_i K_{i+1} d script-K_{n-1}/dK_i
                   + sum_{i,j} K_1 K_i K_j d script-K_{n-1}/dK_{i+j},
      script-K_2 = K_1^2/2,
  with the connected moments C_2 = 32 K_1^2, C_n = 8^n script-K_n (n >= 3)
  [their (A9)-(A14) give C_2..C_7 explicitly] and the full moments from
  M = e^W (Eqs. 21-23).
* Sec. IV (Eqs. 58-64). For a distribution supported on [-x0, inf),
  M(N, y)_{mn} = a_{m+n+1} + y a_{m+n} (0 <= m, n < N) is positive
  semidefinite for y >= x0; y_N = largest root of det M(N, y) = 0 is
  increasing in N with y_inf = lim y_N <= x0 (Eq. 64). They tabulate y_N for
  N <= 32 (Table II, 40-digit Maple) and fit y_N = a + b N^{-1/2} + c/N
  + d N^{-3/2} on 21 <= N <= 33 (Eq. 68), giving y_inf(phidot^2) = 0.02361
  +- 1e-5, which their Eq. (69) offers as the estimate of the optimal bound;
  the caveat at the end of Sec. IV: for a Hamburger-indeterminate moment
  problem y_inf = x_F < x0 (the Friedrichs solution's edge).

What is ours here
-----------------
* The run-structure recursion (A8) is a first-order derivation D on the
  polynomial ring in K_1, K_2, ...; hence script-K_n = D^{n-2} (K_1^2/2)
  = (d/ds)^{n-2} [K_1(s)^2/2]|_{s=0} along the flow
      dK_k/ds = K_{k+1} + K_1 sum_{i+j=k} K_i K_j .
  Evaluated as truncated power series in exact rationals this gives all
  connected moments to any order in seconds, without enumerating the
  ~10^6 run structures at n = 65 (their "2811 terms at n = 30"); it
  reproduces (A9)-(A14) symbolically (checked in the tests).
* On our own kernel (`vacuum.inequalities.qei`, Ford-Roman weight
  `sqrt_lorentzian_f`) the anomalous block is rank one,
  B(w, w') = u(w) u(w')/(2 pi^2), u = w^{3/2} e^{-w tau} sqrt(pi), so the
  necklace traces collapse to the same chain integrals:
      K_n^{(0)} = (2 pi)^{n-1} u^T A^{n-1} u   (tau = 1, p = 3),
  which :func:`kernel_chain_integrals` evaluates by Nystrom quadrature and
  compares with the exact recurrence -- the identification of our operator
  with theirs, normalization included (a_2 = 9/2 is exact by hand:
  (16 pi)^2 (1/2) Tr B^2 = 256 pi^2 (3/8)^2 / (8 pi^2) = 9/2).
* The Stieltjes test: the roots of det(a_{m+n+1} + y a_{m+n}) = 0 are minus
  the zeros of the N-th orthogonal polynomial of the moment sequence (the
  Gauss nodes), so y_N = -(smallest Gauss node); the recurrence coefficients
  are computed exactly (Chebyshev algorithm on the rational moments) and the
  Jacobi-matrix eigenvalues in mpmath -- the well-conditioned form of their
  40-digit determinant computation.
* Carleman/growth diagnostics (Appendix B: a_n ~ power x (3n-4)!) and a
  "blindness" experiment: a point mass added at -x* changes y_N by an amount
  the test cannot resolve, which is the mechanism behind y_inf < x0.

All functions are pure; exact arithmetic uses `fractions.Fraction`,
high-precision linear algebra uses mpmath at the caller's dps.
"""

from __future__ import annotations

import math
from fractions import Fraction
from math import comb, factorial

import numpy as np

__all__ = [
    "FFR2012_Y_INF", "FFR2012_Y_INF_ERR", "FFR2012_TABLE_I", "FFR2012_TABLE_II", "FFR2012_TABLE_III",
    "accelerated_sequence",
    "chain_integrals_exact", "run_structure_cumulants", "moments_from_cumulants",
    "ffr_moment_sequence", "jacobi_recurrence", "stieltjes_edge", "stieltjes_sequence", "ffr_fit_y_inf",
    "carleman_diagnostics", "ffr_identity_A4", "kernel_chain_integrals", "point_mass_perturbation",
]

#: FFR 2012 Eq. (68)-(69): y_inf(phidot^2) = 0.02361 +- 1e-5 (units (4 pi tau^2)^2 rho)
FFR2012_Y_INF, FFR2012_Y_INF_ERR = 0.02361, 1e-5

#: FFR 2012 Table I (rounded to 5 s.f. in print; a_2, a_3 exact): phi^2 (p = 1), phidot^2 (p = 3)
FFR2012_TABLE_I = {
    1: {2: 2.0, 3: 48.0, 4: 1740.0, 5: 83904.0, 6: 5.0516e6, 7: 3.6472e8, 8: 3.0708e10, 9: 2.9538e12,
        10: 3.1956e14, 11: 3.8406e16, 12: 5.0767e18, 13: 7.3196e20, 14: 1.1432e23, 15: 1.9226e25,
        16: 3.4641e27, 17: 6.6572e29, 18: 1.3592e32, 19: 2.9384e34, 20: 6.7046e36, 21: 1.6103e39,
        22: 4.0607e41, 23: 1.0727e44},
    3: {2: 4.5, 3: 1890.0, 4: 2.5516e6, 5: 8.5527e9, 6: 6.0498e13, 7: 7.9890e17, 8: 1.7862e22,
        9: 6.2613e26, 10: 3.2427e31, 11: 2.3696e36, 12: 2.3561e41, 13: 3.0960e46, 14: 5.2487e51,
        15: 1.1252e57, 16: 2.9981e62, 17: 9.7841e67, 18: 3.8605e73, 19: 1.8209e79, 20: 1.0164e85,
        21: 6.6549e90, 22: 5.0695e96, 23: 4.4604e102},
}

#: FFR 2012 Table III: L^{(3/2)} L^{(1)} L^{(1/2)} y_N (phidot^2), labelled N = 21..30 as printed
FFR2012_TABLE_III = {21: 0.02361472123, 22: 0.02361451051, 23: 0.02361432088, 24: 0.02361414978,
                     25: 0.02361399500, 26: 0.02361385460, 27: 0.02361372693, 28: 0.02361361053,
                     29: 0.02361350416, 30: 0.02361340672}


def accelerated_sequence(yN, ks=(0.5, 1.0, 1.5)):
    """FFR Eq. (66)-(67): (L^{(k)} y)_N = (N+1)/k (y_{N+1} - y_N) + y_N, applied for
    each k in `ks` in turn; the result is labelled as in their Table III, i.e.
    the entry using y_N .. y_{N+3} carries the label N + 1 (their N = 21 is
    built from y_20 .. y_23 in this convention; values agree to 11 digits)."""
    seq = dict(yN)
    for k in ks:
        Ns = sorted(seq)
        seq = {N: (N + 1) / k * (seq[N + 1] - seq[N]) + seq[N] for N in Ns[:-1]}
    return {N + 1: v for N, v in seq.items()}


#: FFR 2012 Table II: y_N for phi^2 and phidot^2 (11 printed digits)
FFR2012_TABLE_II = {
    1: {2: 0.08304597359, 3: 0.11085528820, 4: 0.12478398360, 5: 0.13314891433, 6: 0.13872875370,
        7: 0.14271593142, 8: 0.14570717836, 9: 0.14803421582, 10: 0.14989616852, 11: 0.15141979779,
        12: 0.15268963564, 13: 0.15376421805, 14: 0.15468536476, 15: 0.15548374872, 16: 0.15618237796,
        17: 0.15679884907, 18: 0.15734684979, 19: 0.15783718730, 20: 0.15827850807, 21: 0.15867781217,
        22: 0.15904082736, 23: 0.15937228553, 24: 0.15967613018, 25: 0.15995567400, 26: 0.16021372020,
        27: 0.16045265677, 28: 0.16067453067, 29: 0.16088110659, 30: 0.16107391397, 31: 0.16125428495,
        32: 0.16142338519},
    3: {2: 0.01071401240, 3: 0.01414254029, 4: 0.01584995314, 5: 0.01690199565, 6: 0.01762865715,
        7: 0.01816742316, 8: 0.01858660399, 9: 0.01892432539, 10: 0.01920370321, 11: 0.01943965011,
        12: 0.01964226267, 13: 0.01981864633, 14: 0.01997396248, 15: 0.02011206075, 16: 0.02023587746,
        17: 0.02034769569, 18: 0.02044932047, 19: 0.02054219985, 20: 0.02062751059, 21: 0.02070622001,
        22: 0.02077913144, 23: 0.02084691828, 24: 0.02091014970, 25: 0.02096931050, 26: 0.02102481644,
        27: 0.02107702642, 28: 0.02112625203, 29: 0.02117276528, 30: 0.02121680481, 31: 0.02125858099,
        32: 0.02129828002},
}


def chain_integrals_exact(p, n_max):
    """K_n^{(0)}, n = 1..n_max, exactly, by FFR (A6); returns a list with K[0] = None."""
    p = int(p)
    n_max = int(n_max)
    pref = Fraction(factorial(p), 2 ** (p + 1))
    rmax = (p + 2) * n_max + 2
    prev = {r: pref * comb(p + r, p) for r in range(rmax + 1)}
    K = [None, prev[0]]
    for n in range(2, n_max + 1):
        cur = {}
        for r in range(rmax - (p + 2) * (n - 1) + 1):
            cur[r] = pref * comb(p + r, p) * sum(prev[rp] for rp in range(p + r + 2))
        K.append(cur[0])
        prev = cur
    return K


def run_structure_cumulants(K, n_max):
    """Connected dimensionless moments C_2..C_n_max from the chain integrals.

    script-K_n = (d/ds)^{n-2} [K_1(s)^2 / 2] at s = 0 along the flow
    dK_k/ds = K_{k+1} + K_1 sum_{i+j=k} K_i K_j (the flow of FFR's derivation
    (A8)); C_2 = 32 K_1^2, C_n = 8^n script-K_n. `K` may hold Fractions
    (exact) or floats; missing K_k beyond the list are taken as zero, which
    is harmless because K_k first enters script-K_n at n = k + 1.
    """
    n_max = int(n_max)
    M = n_max - 2
    zero = K[1] * 0
    kmax = M + 2
    ser = {k: [zero] * (M + 1) for k in range(1, kmax + 2)}
    for k in range(1, kmax + 2):
        ser[k][0] = K[k] if k < len(K) else zero
    # T_k[m] = coefficient of s^m in sum_{i+j=k} K_i K_j ;  conv_k[m] = coefficient of s^m in K_1 * T_k
    T = {k: [zero] * (M + 1) for k in range(1, kmax + 1)}
    for m in range(M):
        for k in range(1, kmax + 1):
            t = zero
            for i in range(1, k):
                si, sj = ser[i], ser[k - i]
                for a in range(m + 1):
                    t += si[a] * sj[m - a]
            T[k][m] = t
            conv = zero
            for b in range(m + 1):
                conv += ser[1][b] * T[k][m - b]
            rhs = ser[k + 1][m] if (k + 1) in ser else zero
            ser[k][m + 1] = (rhs + conv) / (m + 1)
    k1 = ser[1]
    h = [zero] * (M + 1)
    for a in range(M + 1):
        for b in range(M + 1 - a):
            h[a + b] += k1[a] * k1[b] / 2
    C = [zero] * (n_max + 1)
    C[2] = 32 * K[1] ** 2
    for n in range(3, n_max + 1):
        C[n] = (8 ** n) * h[n - 2] * factorial(n - 2)
    return C


def moments_from_cumulants(C, n_max):
    """a_n from connected moments C_k (a_0 = 1): a_n = sum_k C(n-1, k-1) C_k a_{n-k}."""
    one = C[2] / C[2] if C[2] != 0 else 1
    a = [one] + [C[2] * 0] * n_max
    for n in range(1, n_max + 1):
        a[n] = sum(comb(n - 1, k - 1) * C[k] * a[n - k] for k in range(1, n + 1))
    return a


def ffr_moment_sequence(p=3, n_max=65):
    """FFR's dimensionless vacuum moments a_0..a_n_max, exact rationals, by their Appendix A."""
    K = chain_integrals_exact(p, n_max)
    C = run_structure_cumulants(K, n_max)
    return moments_from_cumulants(C, n_max), C, K


def _to_mpf(x, mp):
    if isinstance(x, Fraction):
        return mp.mpf(x.numerator) / x.denominator
    return mp.mpf(x)


def jacobi_recurrence(a, N):
    """Three-term recurrence coefficients (alpha_k, beta_k), k < N, of the
    monic orthogonal polynomials of the moment sequence a_0..a_{2N-1}, by the
    Chebyshev algorithm (Gautschi, Orthogonal Polynomials, Sec. 2.1.7) in the
    arithmetic of `a` (exact for Fractions). beta_k > 0 for all k < N iff the
    Hankel matrix (a_{m+n})_{m,n<N} is positive definite."""
    N = int(N)
    zero = a[0] * 0
    m = list(a[:2 * N])
    alpha = [m[1] / m[0]]
    beta = [m[0]]
    sig_prev = [zero] * (2 * N)            # sigma_{-1, l}
    sig = list(m)                          # sigma_{0, l}
    for k in range(1, N):
        sig_new = [zero] * (2 * N)
        for l in range(k, 2 * N - k):
            sig_new[l] = sig[l + 1] - alpha[k - 1] * sig[l] - beta[k - 1] * sig_prev[l]
        alpha.append(sig_new[k + 1] / sig_new[k] - sig[k] / sig[k - 1])
        beta.append(sig_new[k] / sig[k - 1])
        sig_prev, sig = sig, sig_new
    return alpha, beta


def stieltjes_edge(a, N, dps=60):
    """y_N of FFR Eq. (63): the largest root of det(a_{m+n+1} + y a_{m+n}) = 0.

    Those roots are minus the zeros of the N-th orthogonal polynomial of the
    moment sequence (the N-point Gauss nodes), so y_N = -(smallest Gauss
    node): the recurrence coefficients are obtained EXACTLY by the Chebyshev
    algorithm on the rational moments and the nodes as the eigenvalues of the
    symmetric tridiagonal Jacobi matrix in mpmath at `dps` -- the
    well-conditioned form of the same computation (a Cholesky of the Hankel
    matrix itself, whose entries span 10^370 at N = 32, is not)."""
    import mpmath as mp

    N = int(N)
    alpha, beta = jacobi_recurrence(a, N)
    with mp.workdps(int(dps)):
        J = mp.matrix(N, N)
        for k in range(N):
            J[k, k] = _to_mpf(alpha[k], mp)
            if k + 1 < N:
                b = _to_mpf(beta[k + 1], mp)
                if b <= 0:
                    raise ValueError(f"beta_{k + 1} = {b} <= 0: not a positive Hankel matrix at N={N}")
                J[k, k + 1] = J[k + 1, k] = mp.sqrt(b)
        ev = mp.eigsy(J, eigvals_only=True)
        return float(-min(ev))


def stieltjes_sequence(a, N_max=32, N_min=2, dps=60):
    """{N: y_N} for N_min <= N <= N_max (needs a up to a_{2 N_max - 1})."""
    return {N: stieltjes_edge(a, N, dps=dps) for N in range(int(N_min), int(N_max) + 1)}


def ffr_fit_y_inf(yN, N_lo=21, N_hi=33):
    """FFR Eq. (68): least squares y_N = a + b N^{-1/2} + c N^{-1} + d N^{-3/2} on N_lo..N_hi."""
    Ns = np.array([N for N in sorted(yN) if N_lo <= N <= N_hi], dtype=float)
    ys = np.array([yN[int(N)] for N in Ns])
    X = np.vstack([np.ones_like(Ns), Ns**-0.5, 1.0 / Ns, Ns**-1.5]).T
    coef, *_ = np.linalg.lstsq(X, ys, rcond=None)
    res = ys - X @ coef
    return {"y_inf": float(coef[0]), "b": float(coef[1]), "c": float(coef[2]), "d": float(coef[3]),
            "max_resid": float(np.max(np.abs(res))), "N_range": [int(Ns[0]), int(Ns[-1])]}


def carleman_diagnostics(a, p=3, shift=1):
    """Growth and Carleman partial sums of a moment sequence.

    Growth: log a_n - log Gamma(3n - 3) for p = 3 (FFR Appendix B: a_n grows
    as a power times (3n - 4)!), whose increments give the geometric factor.
    Carleman: the Hamburger criterion sum_n a_{2n}^{-1/(2n)} = inf and the
    Stieltjes criterion sum_n b_n^{-1/(2n)} = inf on the moments b_n of the
    shifted variable x + shift (support in [0, inf) needs shift >= x0; a_1 = 0
    makes the unshifted Stieltjes sum degenerate) are SUFFICIENT for
    determinacy; for a_n ~ (3n)! both series converge like sum n^{-3/2}, so
    the criteria are inconclusive -- FFR's Sec. I statement -- while a
    density with the Appendix-B tail exp(-c x^{1/3}) is Krein-indeterminate
    (their Sec. VIII remark on Stieltjes' (3n+2)! example)."""
    import mpmath as mp

    n_max = len(a) - 1
    A = [_to_mpf(x, mp) for x in a]
    lg = [0.0] + [float(mp.log(A[n])) for n in range(1, n_max + 1)]
    growth = ({n: lg[n] - math.lgamma(3 * n - 3) for n in range(4, n_max + 1)} if p == 3 else
              {n: lg[n] - math.lgamma(n + 1) for n in range(4, n_max + 1)})
    ham_terms = [math.exp(-lg[2 * n] / (2 * n)) for n in range(1, n_max // 2 + 1)]
    # shifted moments b_n = sum_k C(n,k) shift^{n-k} a_k
    sh = mp.mpf(shift)
    b = [sum(mp.binomial(n, k) * sh ** (n - k) * A[k] for k in range(n + 1)) for n in range(n_max + 1)]
    sti_terms = [float(mp.exp(-mp.log(b[n]) / (2 * n))) for n in range(1, n_max + 1)]
    ns = np.arange(10, n_max + 1)
    return {"log_a_over_gamma": growth,
            "geometric_factor_per_n": float(math.exp(growth[n_max] - growth[n_max - 1])) if p == 3 else None,
            "hamburger_partial_sum": float(np.sum(ham_terms)), "hamburger_last_terms": ham_terms[-3:],
            "hamburger_term_decay_exponent": float(-np.polyfit(np.log(np.arange(5, n_max // 2 + 1)),
                                                               np.log(ham_terms[4:]), 1)[0]),
            "stieltjes_shift": float(shift), "stieltjes_partial_sum": float(np.sum(sti_terms)),
            "stieltjes_last_terms": sti_terms[-3:],
            "stieltjes_term_decay_exponent": float(-np.polyfit(np.log(ns), np.log(sti_terms[9:]), 1)[0]),
            "verdict": "inconclusive (both Carleman series converge; (3n)!-class growth is the Krein-indeterminate class)"}


def ffr_identity_A4(q, kappa, dps=30):
    """FFR (A4), the elementary identity that turns OUR kernel's chain into
    THEIR recurrence: int_0^inf dk k^q e^{-k} e^{-|k - kappa|}
    = q! e^{-kappa} 2^{-(q+1)} sum_{r=0}^{q+1} (2 kappa)^r / r!. Returns
    (direct mpmath quadrature with the cusp split at k = kappa, closed form,
    relative deviation)."""
    import mpmath as mp

    with mp.workdps(int(dps)):
        q = int(q)
        kap = mp.mpf(kappa)
        direct = (mp.quad(lambda k: k**q * mp.exp(-k) * mp.exp(-(kap - k)), [0, kap])
                  + mp.quad(lambda k: k**q * mp.exp(-k) * mp.exp(-(k - kap)), [kap, mp.inf]))
        closed = mp.factorial(q) * mp.exp(-kap) / 2 ** (q + 1) * mp.fsum((2 * kap) ** r / mp.factorial(r)
                                                                          for r in range(q + 2))
        return float(direct), float(closed), float(abs(direct / closed - 1))


def kernel_chain_integrals(f, p=3, n_max=16, grids=((1500, 60.0), (3000, 60.0), (6000, 60.0))):
    """K_n^{(0)} from OUR operator -- through the same code path the solver
    uses -- against FFR's exact recurrence.

    The kernels are built by :func:`vacuum.inequalities.qei._worldline_kernels`
    from :func:`vacuum.inequalities.qei.fhat_of` (exactly what
    `worldline_momentum_minimize` assembles, and the same transform and
    (ww')^{p/2} weighting `box_wavepacket_state` integrates over its boxes):
    A_wk = (ww')^{p/2} Fhat(w - w'), B_wk = (ww')^{p/2} Fhat(w + w') on a
    uniform Gauss-Legendre grid. For the Ford-Roman weight Fhat = pi e^{-|nu|}
    (tau = 1) the anomalous block is rank one, B_wk = pi v v^T with
    v = w^{p/2} e^{-w} (grid-weighted), which is verified here (v is read off
    the diagonal and the residual |B_wk - pi v v^T| reported), and the
    necklace traces reduce to FFR's chain integral (A3) at r = 0:
    K_n = v^T A'^{n-1} v = pi^{-(n-1)} v^T A_wk^{n-1} v. The cusp of the
    transform limits a uniform Nystrom rule to O(h^2), so three grids of equal
    omega_max are Richardson-extrapolated in h^2. Returns per-grid values,
    the extrapolation, the exact values, the worst deviations and the
    rank-one residual. `f` must carry the Ford-Roman weight (tau = 1)."""
    from .qei import _worldline_kernels, fhat_of, momentum_grid

    Kex = chain_integrals_exact(p, n_max)
    fhat = fhat_of(f)
    per_grid = []
    rank_one_resid = 0.0
    for n_modes, om in grids:
        omg, wom = momentum_grid(om, n_modes, power=1)
        A_wk, B_wk = _worldline_kernels(omg, wom, fhat, p)
        A_wk = np.asarray(A_wk).real
        B_wk = np.asarray(B_wk).real
        v = np.sqrt(np.clip(np.diag(B_wk), 0.0, None) / math.pi)
        rank_one_resid = max(rank_one_resid,
                             float(np.max(np.abs(B_wk - math.pi * np.outer(v, v))) / np.max(np.abs(B_wk))))
        vals, x = [], v.copy()
        for n in range(1, n_max + 1):
            vals.append(float(v @ x) / math.pi ** (n - 1))
            if n < n_max:
                x = A_wk @ x
        del A_wk, B_wk
        per_grid.append({"n_modes": int(n_modes), "omega_max": float(om), "h": float(om / n_modes), "K": vals})
    hs = np.array([g["h"] for g in per_grid])
    out = []
    for n in range(1, n_max + 1):
        ks = np.array([gr["K"][n - 1] for gr in per_grid])
        ex = float(Kex[n])
        X = np.vstack([np.ones(len(hs)), hs ** 2]).T
        c2, *_ = np.linalg.lstsq(X, ks, rcond=None)
        devs = np.abs(ks - ex) / abs(ex)
        monotone = bool(np.all((np.diff(devs) < 0) | (devs[1:] < 1e-11))) if len(ks) > 1 else True
        out.append({"n": n, "exact": ex, "nystrom": ks.tolist(), "richardson_h2": float(c2[0]),
                    "rel_dev_finest": float(ks[-1] / ex - 1), "rel_dev_richardson": float(c2[0] / ex - 1),
                    "converging_monotonically": monotone})
    return {"p": int(p), "per_grid": per_grid, "chain": out, "rank_one_residual": rank_one_resid,
            "code_path": "qei._worldline_kernels(momentum_grid(..), fhat_of(f), p)",
            "worst_rel_dev_finest": max(abs(o["rel_dev_finest"]) for o in out),
            "worst_rel_dev_richardson": max(abs(o["rel_dev_richardson"]) for o in out),
            "all_monotone": all(o["converging_monotonically"] for o in out)}


def point_mass_perturbation(a, x_star, weight):
    """Moments of the mixture (1 - weight) P + weight delta(x + x_star): a_n -> (1-w) a_n + w (-x*)^n."""
    w = Fraction(weight) if not isinstance(weight, Fraction) else weight
    xs = Fraction(x_star) if not isinstance(x_star, Fraction) else x_star
    return [(1 - w) * a[n] + w * (-xs) ** n for n in range(len(a))]
