"""vacuum.detectors — particle-detector (UDW) physics of the Vacuum Program.

Layer 2 (docs/PLAN_LAYERS_2_3.md).  This package is the single import
surface for the whole harvesting engine:

- **M2.1 kernels** — Wightman functions (lattice and continuum 3+1
  backends), switching profiles, lattice smearing, and the quadrature
  toolkit the hazard notes prescribe (Gauss-Legendre panels with doubling
  tests, the triangular rule for time-ordered kernels);
- **M2.2 nonperturbative Gaussian stack** — oscillator detectors attached
  to the field coupling matrix, midpoint-rule symplectic evolution with the
  dt-halving convergence gate, Strang-interleaved Gaussian channels with
  automatic ledger dissipation entries, and the mp-margin-safe harvested
  log-negativity;
- **M2.3 perturbative UDW engine** — the second-order two-qubit pair state
  with the PKMM (PRD 92, 064042 (2015)) reference closed forms;
- **M2.5 no-go and communication split** — the Simidzija-Martin-Martinez
  delta-coupling null (``vacuum.detectors.nogo``) and the M_vac / M_comm
  separation (``vacuum.detectors.communication``), both also for the
  derivative coupling (``coupling='xp'``; the d_t phi model of
  Teixido-Bonfill & Martin-Martinez, PRD 110, 105016 (2024), transcribed
  in ``vacuum.detectors.udw_derivative``, nonperturbatively in
  ``attach_detectors(..., coupling='xp')``);
- **M2.6 imperfections** — detector loss, thermal baths and the
  circuit-QED dephasing mapping as checkable (X, Y) Gaussian channels,
  plus the field-temperature route through ``thermal_state_cov``;
- **the experiments loader** — re-exported here as
  ``vacuum.detectors.load_experiment`` (the spelling promised by
  ``experiments/README.md``); it delegates to :mod:`vacuum.experiments_io`,
  which enforces the provenance rules and is the ONE place published units
  are converted to hbar = 1 lattice conventions.

Conventions are docs/API.md throughout: hbar = 1, V_vac = I/2, block
quadrature ordering R = (x_1..x_N, p_1..p_N), entropies/negativities in
nats.  All kernel/switching/smearing/channel objects are frozen data plus
pure functions — no hidden state — pre-positioning for the Layer 6 JAX
mirror.
"""

from vacuum.experiments_io import (
    Experiment,
    Quantity,
    convert_to_lattice,
    list_experiments,
    load_experiment,
)

from .circuit_mapping import (
    R_K_SI,
    PHI_0_REDUCED_SI,
    CRITERIA,
    DEFAULT_CRITERION,
    lambda_tb_from_gamma,
    gamma_from_lambda_tb,
    alpha_from_gamma,
    alpha_from_lambda_tb,
    lambda_tb_from_alpha,
    coupling_energy_SI,
    lattice_wavenumber,
    amplitude_spectral_density,
    derivative_spectral_density,
    golden_rule_rate,
    mapping_factor,
    lambda_udw_from_osc,
    lambda_osc_from_udw,
    lambda_xp_osc_from_tb,
    lambda_osc_from_tb,
    lambda_tb_from_osc,
    ScenarioReadings,
    scenario_lambda_readings,
    MappingResult,
    lambda_osc_from_circuit,
    circuit_from_lambda_osc,
)
from .correlations import (
    TwoModeInvariants,
    two_mode_invariants,
    f_entropy,
    mutual_information,
    minimum_conditional_determinant,
    gaussian_discord,
    classical_correlation,
    GaussianCorrelations,
    gaussian_correlations,
    measurement_covariance,
    conditional_determinant,
    brute_force_gaussian_discord,
    random_two_mode_state,
    fock_ladder,
    fock_quadratures,
    rescale_to_dimensionless,
    fock_density_matrix,
    photon_number_distribution,
    photon_number_distribution_gf,
    shannon_entropy,
    CoherenceResult,
    gaussian_coherence,
    qubit_proxy_from_fock,
    PAULI,
    qubit_pair_from_udw,
    qubit_entropy,
    qubit_marginals,
    qubit_mutual_information,
    qubit_discord,
    qubit_coherence,
    qubit_correlations,
    concurrence,
    qubit_log_negativity,
    pkmm_mutual_information,
    mutual_information_split,
    TomographyPrecision,
    tomography_precision,
    tomography_precision_from_experiment,
    coherence_precision_from_negativity_floor,
    pauli_expectations,
    state_from_pauli,
    project_to_physical,
    noisy_reconstructions,
    batch_qubit_measures,
    monte_carlo_floors,
    floor_state,
    correlation_floors,
)
from .communication import (
    CommunicationSplit,
    RefinableWightmanPart,
    WightmanPart,
    commutator_kernel,
    commutator_term,
    communication_columns,
    communication_estimator,
    communication_split,
    hadamard_kernel,
    pair_state_with_split,
)
from .imperfections import (
    CIRCUIT_QED_KEYS,
    DEPHASING_AXES,
    Imperfections,
    bath_occupation,
    circuit_qed_noise,
    dephasing,
    dephasing_XY,
    detector_loss,
    field_bath_occupations,
    field_thermal_state,
    holevo_werner_margin,
    holevo_werner_matrix,
    imperfection_XY,
    imperfection_channel,
    imperfection_step,
    imperfections_from_rates,
    is_completely_positive,
    loss_channel_XY,
    mode_scaling,
    scale_channel,
    with_imperfections,
)
from .kernels import (
    ContinuumWightman3p1,
    DerivativeKernel,
    ExpSumKernel,
    LatticeWightman,
    RefinableDerivativeKernel,
    derivative_kernel,
    detector_response,
    gl_panels,
    response_gaussian_closed_form,
    triangle_rule,
    wightman_continuum_3p1,
    wightman_lattice,
)
from .nogo import (
    SIMIDZIJA_BASIS,
    DeltaCoupledPair,
    coherent_shift,
    delta_coupled_negativity,
    delta_coupled_overlaps,
    delta_coupled_pair,
    delta_coupled_rho,
    lattice_coherent_shifts,
    partial_transpose_A,
    pt_eigenvalues,
    single_detector_eigenvalues,
    single_detector_rho,
    wightman_triple,
)
from .nonperturbative import (
    EvolveResult,
    FixedRunResult,
    HarvestResult,
    InitialState,
    NegativityResult,
    attach_detectors,
    detector_block,
    detector_coupling_derivative,
    detector_occupations,
    harvested_log_negativity,
    initial_state,
    profile_matrix,
    protocol_evolve,
    protocol_evolve_fixed,
    run_harvesting,
)
from .smearing import Smearing, smearing
from .switching import GAUSSIAN_SUPPORT_SIGMAS, Switching, switching
from .udw_derivative import (
    communication_split_derivative,
    derivative_detector,
    derivative_pair_kernels,
    pair_state_with_split_derivative,
    response_mode_sum,
    spatial_derivative_profile,
    switching_fourier,
    udw_pair_state_derivative,
)
from .udw import (
    COUPLINGS,
    PKMM_NONOVERLAP_GAMMA,
    PKMM_SWITCHING_WIDTH_FACTOR,
    UDWDetector,
    UDWPairState,
    cross_term,
    pair_kernels,
    pair_log_negativity,
    pair_negativity,
    pair_term,
    pkmm_detectors,
    pkmm_L_AA,
    pkmm_L_AB,
    pkmm_M_abs,
    pkmm_M_abs_coincident_pointlike,
    pkmm_M_abs_nonoverlap,
    pkmm_negativity_estimator,
    pkmm_pair_state,
    transition_probability,
    udw_pair_state,
)

__all__ = [
    # kernels (M2.1)
    "LatticeWightman",
    "ExpSumKernel",
    "DerivativeKernel",
    "RefinableDerivativeKernel",
    "derivative_kernel",
    "ContinuumWightman3p1",
    "wightman_lattice",
    "wightman_continuum_3p1",
    "detector_response",
    "response_gaussian_closed_form",
    "gl_panels",
    "triangle_rule",
    # switching (M2.1)
    "Switching",
    "switching",
    "GAUSSIAN_SUPPORT_SIGMAS",
    # smearing (M2.1)
    "Smearing",
    "smearing",
    # nonperturbative stack (M2.2)
    "attach_detectors",
    "profile_matrix",
    "detector_coupling_derivative",
    "initial_state",
    "InitialState",
    "protocol_evolve",
    "protocol_evolve_fixed",
    "EvolveResult",
    "FixedRunResult",
    "detector_block",
    "detector_occupations",
    "harvested_log_negativity",
    "NegativityResult",
    "run_harvesting",
    "HarvestResult",
    # perturbative UDW engine (M2.3)
    "COUPLINGS",
    "UDWDetector",
    "UDWPairState",
    "udw_pair_state",
    "pair_kernels",
    "transition_probability",
    "cross_term",
    "pair_term",
    "pair_negativity",
    "pair_log_negativity",
    # PKMM (PRD 92, 064042 (2015)) reference closed forms
    "PKMM_SWITCHING_WIDTH_FACTOR",
    "PKMM_NONOVERLAP_GAMMA",
    "pkmm_L_AA",
    "pkmm_L_AB",
    "pkmm_M_abs",
    "pkmm_M_abs_nonoverlap",
    "pkmm_M_abs_coincident_pointlike",
    "pkmm_negativity_estimator",
    "pkmm_detectors",
    "pkmm_pair_state",
    # derivative coupling, perturbative side of 'xp' (M2.5 / Layer 2 target)
    "derivative_pair_kernels",
    "udw_pair_state_derivative",
    "communication_split_derivative",
    "pair_state_with_split_derivative",
    "switching_fourier",
    "response_mode_sum",
    "spatial_derivative_profile",
    "derivative_detector",
    # no-go: the Simidzija-Martin-Martinez delta-coupling null (M2.5)
    "DeltaCoupledPair",
    "delta_coupled_pair",
    "delta_coupled_overlaps",
    "delta_coupled_rho",
    "delta_coupled_negativity",
    "partial_transpose_A",
    "pt_eigenvalues",
    "single_detector_rho",
    "single_detector_eigenvalues",
    "coherent_shift",
    "lattice_coherent_shifts",
    "wightman_triple",
    "SIMIDZIJA_BASIS",
    # communication split M_vac / M_comm (M2.5)
    "CommunicationSplit",
    "WightmanPart",
    "RefinableWightmanPart",
    "commutator_kernel",
    "hadamard_kernel",
    "commutator_term",
    "communication_split",
    "communication_estimator",
    "pair_state_with_split",
    "communication_columns",
    # imperfections (M2.6)
    "DEPHASING_AXES",
    "Imperfections",
    "with_imperfections",
    "imperfection_XY",
    "imperfection_channel",
    "imperfection_step",
    "dephasing",
    "dephasing_XY",
    "detector_loss",
    "loss_channel_XY",
    "mode_scaling",
    "scale_channel",
    "holevo_werner_matrix",
    "holevo_werner_margin",
    "is_completely_positive",
    "bath_occupation",
    "field_thermal_state",
    "field_bath_occupations",
    "imperfections_from_rates",
    "circuit_qed_noise",
    "CIRCUIT_QED_KEYS",
    # experiments loader (M-I I.3), re-exported per experiments/README.md
    "load_experiment",
    "list_experiments",
    "convert_to_lattice",
    "Experiment",
    "Quantity",
    "R_K_SI",
    "PHI_0_REDUCED_SI",
    "CRITERIA",
    "DEFAULT_CRITERION",
    "lambda_tb_from_gamma",
    "gamma_from_lambda_tb",
    "alpha_from_gamma",
    "alpha_from_lambda_tb",
    "lambda_tb_from_alpha",
    "coupling_energy_SI",
    "lattice_wavenumber",
    "amplitude_spectral_density",
    "derivative_spectral_density",
    "golden_rule_rate",
    "mapping_factor",
    "lambda_udw_from_osc",
    "lambda_osc_from_udw",
    "lambda_xp_osc_from_tb",
    "lambda_osc_from_tb",
    "lambda_tb_from_osc",
    "ScenarioReadings",
    "scenario_lambda_readings",
    "MappingResult",
    "lambda_osc_from_circuit",
    "circuit_from_lambda_osc",
    "TwoModeInvariants",
    "two_mode_invariants",
    "f_entropy",
    "mutual_information",
    "minimum_conditional_determinant",
    "gaussian_discord",
    "classical_correlation",
    "GaussianCorrelations",
    "gaussian_correlations",
    "measurement_covariance",
    "conditional_determinant",
    "brute_force_gaussian_discord",
    "random_two_mode_state",
    "fock_ladder",
    "fock_quadratures",
    "rescale_to_dimensionless",
    "fock_density_matrix",
    "photon_number_distribution",
    "photon_number_distribution_gf",
    "shannon_entropy",
    "CoherenceResult",
    "gaussian_coherence",
    "qubit_proxy_from_fock",
    "PAULI",
    "qubit_pair_from_udw",
    "qubit_entropy",
    "qubit_marginals",
    "qubit_mutual_information",
    "qubit_discord",
    "qubit_coherence",
    "qubit_correlations",
    "concurrence",
    "qubit_log_negativity",
    "pkmm_mutual_information",
    "mutual_information_split",
    "TomographyPrecision",
    "tomography_precision",
    "tomography_precision_from_experiment",
    "coherence_precision_from_negativity_floor",
    "pauli_expectations",
    "state_from_pauli",
    "project_to_physical",
    "noisy_reconstructions",
    "batch_qubit_measures",
    "monte_carlo_floors",
    "floor_state",
    "correlation_floors",
]
