"""Detector imperfections: loss, thermal bath, dephasing (Layer 2, M2.6).

Spec: ``with_imperfections(V, eta, nbar, dephasing)`` composes
``vacuum.core.channels`` on the *detector* modes of a harvesting protocol;
the field-side temperature enters through
``vacuum.core.thermal_state_cov``.  Everything here is a pure function over
arrays (no hidden state, no input mutation) — Layer 6 JAX-mirror
pre-positioning — and every channel is returned in ``(X, Y)`` form so its
complete positivity is *checkable*, not asserted.

Complete positivity (Holevo-Werner)
-----------------------------------
A Gaussian channel V -> X V X^T + Y is completely positive iff

    Y + (i/2) (Omega - X Omega X^T)  >=  0                            (CP)

as a Hermitian matrix (A. S. Holevo, R. F. Werner, Phys. Rev. A 63, 032312
(2001), Eq. (3.4); A. Serafini, "Quantum Continuous Variables", CRC 2017,
Sec. 5.3), with Omega the block-ordered symplectic form of docs/API.md.
:func:`holevo_werner_matrix` builds the left-hand side and
:func:`is_completely_positive` tests it; the module's channels satisfy it
by construction and the test suite checks every one of them.

The frequency-scaling rule
--------------------------
``vacuum.core.channels`` is written in the dimensionless convention where
the vacuum covariance is I/2.  A detector oscillator of gap Omega_d,
however, lives in H_d = (1/2)(p^2 + Omega_d^2 x^2), whose ground state is
V = diag(1/(2 Omega_d), Omega_d/2) — *not* I/2.  Applying a bare core
channel to such a mode would relax it toward the wrong state.  So every
channel here is conjugated by the (symplectic, diagonal) rescaling

    Sigma_d = diag(sqrt(Omega_d), 1/sqrt(Omega_d))    (x-row, p-row)

which maps the mode to its dimensionless quadratures:

    X' = Sigma^{-1} X Sigma,      Y' = Sigma^{-1} Y Sigma^{-1}.

Because Sigma is real and symplectic, the (CP) matrix transforms by the
congruence M -> Sigma^{-1} M Sigma^{-1}, so CP is preserved exactly — a
theorem this module tests rather than assumes.  With ``gaps=None`` every
Omega_d is 1 and the channels reduce *identically* to the bare
``vacuum.core.channels`` maps.

Consequence worth stating: loss with eta -> 0 and bath occupation
nbar = 1/(e^{Omega_d/T} - 1) drives the detector exactly to
``thermal_state_cov([[Omega_d^2]], T)`` — the detector bath and the field
bath are then the same temperature, described by the same formula.

The circuit-QED dephasing mapping (chosen, documented)
------------------------------------------------------
In circuit QED the dominant detector dephasing is low-frequency flux (or
charge) noise that jitters the detector frequency; for a *qubit* that is
the sigma_z coupling with pure-dephasing rate Gamma_phi, e.g. the
transmission-line contribution Gamma_phi^TL = 2 k_B T phi_0^2
|gamma_{5,11} - gamma_{5,00}|^2 / (hbar^2 Z_0) of N. Janzen, X. Dai,
S. Ren, J. Shi, A. Lupascu, Phys. Rev. Research 5, 033155 (2023), Eq. (15)
(arXiv:2208.05571).

Mapping that onto the *harmonic* (Gaussian) detector of the M2.2 stack
needs care, and the choice is made explicitly here:

1. The literal oscillator transcription of frequency jitter is the
   number-dephasing Lindbladian L = sqrt(2 Gamma_phi) a^dag a.  Its second
   moments do close — <a^dag a> is conserved while <a^2> decays as
   e^{-4 Gamma_phi t} — but the induced map on the covariance,

       V -> (nbar_V + 1/2) I + e^{-4 Gamma_phi t} (V - (nbar_V + 1/2) I),

   depends on the *state* through nbar_V = Tr(V~)/2 - 1/2.  It is
   therefore NOT of the form V -> X V X^T + Y: number dephasing is not a
   Gaussian channel, and it is deliberately not used here.

2. The Gaussian channel that *is* phase-covariant (it commutes with the
   free rotation e^{-i Omega_d t a^dag a}, which is a rigid rotation in the
   rescaled quadratures) is the classical-noise channel generated by
   Hermitian *linear* Lindblad operators — the standard Gaussian
   dephasing/diffusion channel:

       drho/dt = (Gamma_phi/2) ( D[x~] + D[p~] ) rho,
       D[A] rho = 2 A rho A - A^2 rho - rho A^2 = -[A, [A, rho]],

   giving dV~/dt = Gamma_phi I_2, i.e. over a window tau

       X = I,   Y~ = D I_2,   D = Gamma_phi * tau.               (chosen)

   This is exactly ``vacuum.core.channels.thermal_noise`` with
   nbar_added = D, conjugated by the frequency rescaling.  CP is immediate:
   X = I makes (CP) read Y >= 0.

3. The spec's alternative — "``thermal_noise`` on p only" — is the
   single-quadrature version, one Hermitian Lindblad operator
   L = sqrt(2 Gamma_phi) x~ (random momentum kicks; the Caldeira-Leggett /
   position-localization form).  It is offered as ``axis='p'`` (and
   ``axis='x'``), normalized to add the *same* total quadrature variance
   as the isotropic map, Y~ = 2 D e_p e_p^T (equal Tr Y~ = 2 D, hence equal
   added energy), so the two mappings differ only in their anisotropy.

Both are additive-classical-noise (X = I) channels, hence CP for D >= 0,
non-unital in energy — they heat the detector, and the M2.2/protocol
ledgers book that heating as a (negative) dissipation entry automatically.

Rates in, channel parameters out
--------------------------------
:func:`imperfections_from_rates` converts a relaxation rate Gamma_1, a pure
dephasing rate Gamma_phi and a bath temperature T (all in the program's
hbar = k_B = 1 lattice units — ``vacuum.experiments_io`` is the only place
physical units are converted) into (eta, nbar, D) over an interaction
window tau:

    eta = exp(-Gamma_1 tau),   nbar = 1/(e^{Omega_d/T} - 1),
    D   = Gamma_phi (1 - eta) / Gamma_1   ( -> Gamma_phi tau as Gamma_1 -> 0),

the last being the *exact* integral of the combined Lindbladian rather
than a product of separately integrated pieces — see
:func:`imperfection_channel` for why that distinction sets the order of
the Trotter splitting.

:func:`circuit_qed_noise` does the same starting from a validated
``experiments/`` parameter file, so a sweep row inherits its provenance.

Conventions per docs/API.md: hbar = k_B = 1, V_vac = I/2 (dimensionless
quadratures), nu >= 1/2, block ordering R = (x_1..x_N, p_1..p_N).
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional, Tuple

import numpy as np

from vacuum.core import Omega as symplectic_form
from vacuum.core import apply_channel, ground_state_cov, thermal_state_cov
from vacuum.core.channels import loss_XY, thermal_noise_XY
from vacuum.experiments_io import bose_occupation, load_experiment

__all__ = [
    "DEPHASING_AXES",
    "Imperfections",
    "holevo_werner_matrix",
    "holevo_werner_margin",
    "is_completely_positive",
    "mode_scaling",
    "scale_channel",
    "loss_channel_XY",
    "dephasing_XY",
    "dephasing",
    "detector_loss",
    "imperfection_XY",
    "with_imperfections",
    "imperfection_channel",
    "imperfection_step",
    "bath_occupation",
    "field_thermal_state",
    "field_bath_occupations",
    "imperfections_from_rates",
    "circuit_qed_noise",
]

#: Dephasing anisotropy options (see the module docstring, item 2/3).
DEPHASING_AXES = ("isotropic", "p", "x")


# --------------------------------------------------------------------------
# Complete positivity: the Holevo-Werner condition, made checkable
# --------------------------------------------------------------------------


def holevo_werner_matrix(X, Y):
    """Hermitian matrix of the CP condition: Y + (i/2)(Omega - X Omega X^T).

    Holevo-Werner, Phys. Rev. A 63, 032312 (2001), Eq. (3.4): a Gaussian
    map V -> X V X^T + Y is completely positive iff this matrix is positive
    semidefinite (Omega in the block ordering of docs/API.md).
    """
    X = np.asarray(X, dtype=float)
    Y = np.asarray(Y, dtype=float)
    if X.shape != Y.shape or X.ndim != 2 or X.shape[0] != X.shape[1]:
        raise ValueError(f"X, Y must be equal square matrices, got {X.shape}, {Y.shape}")
    N = X.shape[0] // 2
    if X.shape[0] != 2 * N:
        raise ValueError(f"X, Y must have even dimension, got {X.shape[0]}")
    Om = symplectic_form(N)
    return Y.astype(complex) + 0.5j * (Om - X @ Om @ X.T)


def holevo_werner_margin(X, Y):
    """Smallest eigenvalue of :func:`holevo_werner_matrix` (>= 0 iff CP).

    The *margin* is reported (not a bool) so failures print a number, per
    the repo's testing convention.
    """
    return float(np.min(np.linalg.eigvalsh(holevo_werner_matrix(X, Y))))


def is_completely_positive(X, Y, tol=1e-12):
    """True iff the Holevo-Werner margin is >= -tol (roundoff-tolerant)."""
    return holevo_werner_margin(X, Y) >= -abs(float(tol))


# --------------------------------------------------------------------------
# Frequency rescaling of a detector mode
# --------------------------------------------------------------------------


def _mode_list(N, modes):
    m = tuple(int(k) for k in modes)
    if not m:
        raise ValueError("need at least one mode index")
    if len(set(m)) != len(m):
        raise ValueError(f"repeated mode index in {m}")
    for k in m:
        if not 0 <= k < N:
            raise IndexError(f"mode index {k} out of range for N={N}")
    return m


def _gap_array(modes, gaps):
    """Per-mode gaps, broadcast from a scalar; None -> all ones."""
    n = len(modes)
    if gaps is None:
        return np.ones(n)
    g = np.asarray(gaps, dtype=float)
    if g.ndim == 0:
        g = np.full(n, float(g))
    if g.shape != (n,):
        raise ValueError(f"gaps shape {g.shape} != ({n},) (one gap per mode)")
    if np.any(g <= 0.0):
        raise ValueError(f"detector gaps must be > 0, got {g}")
    return g


def mode_scaling(N, modes, gaps):
    """Diagonal of the symplectic rescaling Sigma to dimensionless quadratures.

    Returns the length-2N diagonal of Sigma: sqrt(Omega_d) on the x row and
    1/sqrt(Omega_d) on the p row of each listed mode, 1 elsewhere.  Sigma is
    symplectic (each mode block has determinant 1 and is diagonal), so
    conjugating a channel by it preserves complete positivity exactly (see
    the module docstring).  ``gaps=None`` returns all ones.
    """
    N = int(N)
    m = _mode_list(N, modes)
    g = _gap_array(m, gaps)
    s = np.ones(2 * N)
    for k, gap in zip(m, g):
        s[k] = math.sqrt(gap)
        s[N + k] = 1.0 / math.sqrt(gap)
    return s


def scale_channel(X, Y, s):
    """Conjugate a channel by the diagonal rescaling with diagonal `s`.

    X' = Sigma^{-1} X Sigma, Y' = Sigma^{-1} Y Sigma^{-1} with
    Sigma = diag(s) — the channel written in the original (unscaled)
    quadratures.  Pure function; inputs are not mutated.
    """
    X = np.asarray(X, dtype=float)
    Y = np.asarray(Y, dtype=float)
    s = np.asarray(s, dtype=float)
    inv = 1.0 / s
    Xp = (inv[:, None] * X) * s[None, :]
    Yp = (inv[:, None] * Y) * inv[None, :]
    return Xp, Yp


# --------------------------------------------------------------------------
# The channels
# --------------------------------------------------------------------------


def loss_channel_XY(N, modes, eta, nbar=0.0, gaps=None):
    """(X, Y) for detector loss into a thermal bath, frequency-aware.

    ``vacuum.core.channels.loss_XY`` in the mode's dimensionless
    quadratures, conjugated by :func:`mode_scaling`.  With ``gaps=None``
    this *is* ``loss_XY``.  At eta -> 0 the mode is replaced by
    (nbar + 1/2) diag(1/Omega_d, Omega_d) — exactly
    ``thermal_state_cov([[Omega_d^2]], T)`` for the bath occupation
    nbar = 1/(e^{Omega_d/T} - 1).
    """
    N = int(N)
    m = _mode_list(N, modes)
    X, Y = loss_XY(N, m, eta, nbar)
    if gaps is None:
        return X, Y
    return scale_channel(X, Y, mode_scaling(N, m, gaps))


def dephasing_XY(N, modes, D, axis="isotropic", gaps=None):
    """(X, Y) for the Gaussian dephasing channel (module docstring, item 2).

    Parameters
    ----------
    N : int
        Total number of modes.
    modes : sequence of int
        Modes to dephase (the detector modes).
    D : float
        Integrated dephasing strength, D = Gamma_phi * tau >= 0, in the
        dimensionless quadratures (added variance per quadrature for
        ``axis='isotropic'``).
    axis : {'isotropic', 'p', 'x'}
        'isotropic' (default, phase-covariant): Y~ = D I_2 per mode — the
        chosen circuit-QED mapping.  'p' / 'x': single-quadrature diffusion
        normalized to the same total added variance, Y~ = 2 D e_p e_p^T
        (resp. e_x e_x^T) — the spec's "thermal_noise on p only" variant.
    gaps : float, sequence or None
        Detector frequencies for the rescaling (None: dimensionless modes).

    Notes
    -----
    X = I always, so the Holevo-Werner condition reduces to Y >= 0, i.e.
    the channel is CP for every D >= 0 and every axis.
    """
    N = int(N)
    m = _mode_list(N, modes)
    D = float(D)
    if D < 0.0:
        raise ValueError(f"dephasing strength D must be >= 0, got {D}")
    if axis not in DEPHASING_AXES:
        raise ValueError(f"axis must be one of {DEPHASING_AXES}, got {axis!r}")
    if axis == "isotropic":
        X, Y = thermal_noise_XY(N, m, D)
    else:
        X = np.eye(2 * N)
        Y = np.zeros((2 * N, 2 * N))
        off = 0 if axis == "x" else N
        for k in m:
            Y[off + k, off + k] = 2.0 * D
    if gaps is None:
        return X, Y
    return scale_channel(X, Y, mode_scaling(N, m, gaps))


def dephasing(V, modes, D, axis="isotropic", gaps=None):
    """Apply the Gaussian dephasing channel to `modes` of V (pure function)."""
    V = np.asarray(V, dtype=float)
    N = V.shape[0] // 2
    X, Y = dephasing_XY(N, modes, D, axis=axis, gaps=gaps)
    return apply_channel(V, X, Y)


def detector_loss(V, modes, eta, nbar=0.0, gaps=None):
    """Apply frequency-aware loss to `modes` of V (pure function)."""
    V = np.asarray(V, dtype=float)
    N = V.shape[0] // 2
    X, Y = loss_channel_XY(N, modes, eta, nbar, gaps=gaps)
    return apply_channel(V, X, Y)


def imperfection_XY(N, modes, eta=1.0, nbar=0.0, dephasing=0.0, axis="isotropic",
                    gaps=None):
    """(X, Y) of the composed imperfection map: loss first, then dephasing.

    Composition of Gaussian channels (X2, Y2) o (X1, Y1) is
    (X2 X1, X2 Y1 X2^T + Y2); here X2 = I (dephasing is additive noise), so

        X = sqrt(eta) on the listed modes,   Y = Y_loss + Y_dephasing,

    both written in the original quadratures via :func:`mode_scaling`.
    The two pieces do NOT commute in general — dephasing first would give
    Y = eta Y_dephasing + Y_loss, a difference of order (1 - eta) D — and
    this module fixes the order as *loss then dephasing* (the noise added
    after the lossy interaction window is not attenuated by it).
    """
    N = int(N)
    m = _mode_list(N, modes)
    Xl, Yl = loss_channel_XY(N, m, eta, nbar, gaps=gaps)
    Xd, Yd = dephasing_XY(N, m, dephasing, axis=axis, gaps=gaps)
    return Xd @ Xl, Xd @ Yl @ Xd.T + Yd


def with_imperfections(V, modes, eta=1.0, nbar=0.0, dephasing=0.0,
                       axis="isotropic", gaps=None):
    """Compose detector loss and dephasing on `modes` of V (spec M2.6).

    The spec's ``with_imperfections(V, eta, nbar, dephasing)`` plus the
    mandatory mode set (which modes are the detectors is protocol
    information, not state information) and the optional detector gaps that
    make the channels frequency-aware.

    Parameters
    ----------
    V : (2N, 2N) ndarray
        Covariance (never mutated).
    modes : sequence of int
        Detector mode indices, e.g. ``range(N_field, N_tot)``.
    eta : float in [0, 1]
        Transmissivity of the detector loss channel; eta = exp(-Gamma_1 tau)
        for an energy-relaxation rate Gamma_1 over a window tau.  eta = 1 is
        the identity.
    nbar : float >= 0
        Bath occupation of the loss environment (see :func:`bath_occupation`).
    dephasing : float >= 0
        Integrated dephasing D = Gamma_phi * tau.
    axis : {'isotropic', 'p', 'x'}
        Dephasing anisotropy (see :func:`dephasing_XY`).
    gaps : float, sequence or None
        Detector frequencies Omega_d.  None keeps the bare dimensionless
        ``vacuum.core.channels`` convention.

    Returns
    -------
    (2N, 2N) ndarray
        ``dephasing(loss(V))`` — identical to
        ``apply_channel(V, *imperfection_XY(...))`` to roundoff.
    """
    V = np.asarray(V, dtype=float)
    N = V.shape[0] // 2
    X, Y = imperfection_XY(
        N, modes, eta=eta, nbar=nbar, dephasing=dephasing, axis=axis, gaps=gaps
    )
    return apply_channel(V, X, Y)


@dataclass(frozen=True)
class Imperfections:
    """Frozen record of a detector's imperfection parameters.

    Carries exactly the arguments of :func:`with_imperfections` (minus the
    state), so a sweep row can store the noise model it ran under.
    ``provenance`` names the ``experiments/`` file the numbers came from
    when they were loaded rather than chosen.
    """

    eta: float = 1.0
    nbar: float = 0.0
    dephasing: float = 0.0
    axis: str = "isotropic"
    gaps: Optional[Tuple[float, ...]] = None
    tau: Optional[float] = None
    provenance: Optional[str] = None

    def apply(self, V, modes):
        """Apply this noise model to `modes` of V."""
        return with_imperfections(
            V,
            modes,
            eta=self.eta,
            nbar=self.nbar,
            dephasing=self.dephasing,
            axis=self.axis,
            gaps=self.gaps,
        )

    def XY(self, N, modes):
        """(X, Y) of this noise model on an N-mode system."""
        return imperfection_XY(
            N,
            modes,
            eta=self.eta,
            nbar=self.nbar,
            dephasing=self.dephasing,
            axis=self.axis,
            gaps=self.gaps,
        )

    def is_identity(self, tol=0.0):
        """True iff the map is the identity channel (no loss, no dephasing)."""
        return abs(self.eta - 1.0) <= tol and abs(self.dephasing) <= tol


# --------------------------------------------------------------------------
# Adapters: the two protocol entry points
# --------------------------------------------------------------------------


def imperfection_channel(modes, kappa=0.0, nbar=0.0, gamma_phi=0.0,
                         axis="isotropic", gaps=None):
    """Rate-based channel callable ``(V, t, dt) -> V`` for ``protocol_evolve``.

    ``vacuum.detectors.protocol_evolve`` interleaves channels in a Strang
    splitting and hands each one the substep duration, so the channel must
    own its dt-scaling for the Trotter limit to converge (spec M2.2).  This
    factory returns the EXACT propagator of the combined Lindbladian over a
    duration dt — damping at rate `kappa` toward a bath of occupation
    `nbar`, plus dephasing diffusion at rate `gamma_phi` — not a product of
    separately integrated pieces.  In the rescaled quadratures the combined
    generator is linear,

        dV~/dt = -kappa (V~ - (nbar + 1/2) I) + gamma_phi * G,
        G = I_2 (isotropic) or 2 e_p e_p^T (axis='p'), and its solution is

        eta = exp(-kappa dt),    D = gamma_phi (1 - eta) / kappa,

    which is exactly :func:`with_imperfections` at those arguments and
    reduces to D = gamma_phi dt as kappa -> 0 (computed stably with expm1).

    This matters for the splitting order: a semigroup composes,
    C_{dt/2} o C_{dt/2} = C_{dt}, so the two Strang half-applications join
    with no error and the interleaved evolution stays *second* order in dt,
    set by the Magnus stepper alone.  Integrating loss and dephasing
    separately and composing them would leave an O(dt) commutator error and
    drop the dt-halving gate to first order.

    The returned closure is pure: it captures only frozen parameters and
    ignores the absolute time t (a time-dependent noise schedule would
    take t).
    """
    m = tuple(int(k) for k in modes)
    kappa = float(kappa)
    gamma_phi = float(gamma_phi)
    if kappa < 0.0:
        raise ValueError(f"kappa must be >= 0, got {kappa}")
    if gamma_phi < 0.0:
        raise ValueError(f"gamma_phi must be >= 0, got {gamma_phi}")
    if axis not in DEPHASING_AXES:
        raise ValueError(f"axis must be one of {DEPHASING_AXES}, got {axis!r}")
    gaps_t = None if gaps is None else tuple(np.atleast_1d(np.asarray(gaps, float)))

    def channel(V, t, dt):
        dt = float(dt)
        eta = math.exp(-kappa * dt)
        # (1 - e^{-kappa dt}) / kappa, stable in both limits (-> dt at kappa=0)
        window = dt if kappa == 0.0 else -math.expm1(-kappa * dt) / kappa
        return with_imperfections(
            V,
            m,
            eta=eta,
            nbar=nbar,
            dephasing=gamma_phi * window,
            axis=axis,
            gaps=gaps_t,
        )

    return channel


def imperfection_step(modes, eta=1.0, nbar=0.0, dephasing=0.0, axis="isotropic",
                      gaps=None, label="imperfections"):
    """A :class:`vacuum.protocol.ChannelStep` applying :func:`with_imperfections`.

    The instantaneous (already-integrated) form, for protocols assembled as
    a step list and run through :func:`vacuum.protocol.run_protocol`: the
    runner books the channel's mean-energy change as a ledger ``dissipate``
    entry, so the books close automatically.
    """
    from vacuum.protocol import ChannelStep  # local import: keeps this module light

    return ChannelStep(
        channel=with_imperfections,
        args=(tuple(int(k) for k in modes),),
        kwargs={
            "eta": float(eta),
            "nbar": float(nbar),
            "dephasing": float(dephasing),
            "axis": axis,
            "gaps": gaps,
        },
        label=label,
    )


# --------------------------------------------------------------------------
# Temperatures: the field side (thermal_state_cov) and the detector bath
# --------------------------------------------------------------------------


def bath_occupation(omega, T):
    """Bose occupation nbar = 1/(e^{omega/T} - 1) in lattice units.

    Thin, documented wrapper on ``vacuum.experiments_io.bose_occupation``
    (hbar = k_B = 1: only the ratio omega/T enters).  T = 0 gives 0.
    Accepts an array of frequencies.
    """
    w = np.asarray(omega, dtype=float)
    if w.ndim == 0:
        return bose_occupation(float(w), float(T))
    return np.array([bose_occupation(float(x), float(T)) for x in w])


def field_thermal_state(K, T):
    """Field covariance at temperature T (spec M2.6: via ``thermal_state_cov``).

    The field side of "imperfections" is temperature, and it enters exactly
    one way: ``vacuum.core.thermal_state_cov(K, T)``, whose T = 0 branch
    reproduces ``ground_state_cov(K)`` identically.  This wrapper exists so
    that a harvesting protocol never hand-rolls a thermal covariance;
    it forwards unchanged.
    """
    T = float(T)
    if T < 0.0:
        raise ValueError(f"temperature must be >= 0, got {T}")
    if T == 0.0:
        return ground_state_cov(K)
    return thermal_state_cov(K, T)


def field_bath_occupations(K, T):
    """Per-normal-mode occupations of the thermal field state.

    With K = U diag(omega^2) U^T, returns (omega, nbar) with
    nbar_k = 1/(e^{omega_k/T} - 1) — the occupations whose
    sum_k omega_k (nbar_k + 1/2) is ``mean_energy(thermal_state_cov(K, T), K)``.
    """
    K = np.asarray(K, dtype=float)
    w2 = np.linalg.eigvalsh(0.5 * (K + K.T))
    if np.min(w2) <= 0.0:
        raise ValueError(
            f"K must be positive definite for a thermal state: min eig {np.min(w2):.3e}"
        )
    omega = np.sqrt(w2)
    return omega, bath_occupation(omega, T)


# --------------------------------------------------------------------------
# Rates -> channel parameters (and the provenance bridge)
# --------------------------------------------------------------------------


def imperfections_from_rates(gaps, tau, T=0.0, Gamma_1=0.0, Gamma_phi=0.0,
                             axis="isotropic", provenance=None):
    """Map physical rates over a window tau to an :class:`Imperfections`.

    All arguments are in the program's lattice units (hbar = k_B = 1);
    ``vacuum.experiments_io`` is the only place SI values are converted.

        eta  = exp(-Gamma_1 tau)                 (energy relaxation)
        nbar = 1/(e^{Omega_d/T} - 1)             (bath occupation at the gap)
        D    = Gamma_phi (1 - eta) / Gamma_1     (integrated pure dephasing)

    The dephasing integral is the exact solution of the *combined*
    Lindbladian (:func:`imperfection_channel`), not Gamma_phi * tau, which
    it reduces to as Gamma_1 -> 0; the two differ at order Gamma_1 tau and
    the exact form is what makes the map a semigroup.  Consequently
    ``imperfections_from_rates(gaps, tau, T, G1, Gphi).apply(V, modes)``
    equals ``imperfection_channel(modes, G1, nbar, Gphi, gaps=gaps)(V, t,
    tau)`` identically.

    A single bath occupation is used, evaluated at the *mean* detector gap
    when the gaps differ, and the per-detector gaps are kept for the
    frequency rescaling; harvesting protocols use equal-gap detector pairs,
    and unequal gaps with a shared bath would need one channel per detector
    (call :func:`with_imperfections` per mode in that case).
    """
    g = np.atleast_1d(np.asarray(gaps, dtype=float))
    if np.any(g <= 0.0):
        raise ValueError(f"detector gaps must be > 0, got {g}")
    tau = float(tau)
    if tau < 0.0:
        raise ValueError(f"tau must be >= 0, got {tau}")
    Gamma_1 = float(Gamma_1)
    Gamma_phi = float(Gamma_phi)
    if Gamma_1 < 0.0 or Gamma_phi < 0.0:
        raise ValueError(
            f"rates must be >= 0, got Gamma_1={Gamma_1}, Gamma_phi={Gamma_phi}"
        )
    eta = math.exp(-Gamma_1 * tau)
    window = tau if Gamma_1 == 0.0 else -math.expm1(-Gamma_1 * tau) / Gamma_1
    return Imperfections(
        eta=eta,
        nbar=bath_occupation(float(np.mean(g)), T),
        dephasing=Gamma_phi * window,
        axis=axis,
        gaps=tuple(float(x) for x in g),
        tau=tau,
        provenance=provenance,
    )


#: Default quantity names read by :func:`circuit_qed_noise` from an
#: ``experiments/circuit_qed_harvesting/`` file.  They are the names used by
#: the files this milestone ships; pass explicit keys for other schemas.
CIRCUIT_QED_KEYS = {
    "gap": "qubit_gap_frequency",
    "relaxation": "relaxation_rate_gamma1_max",
    "dephasing": "pure_dephasing_rate_max",
    "temperature": "transmission_line_temperature",
}


def circuit_qed_noise(experiment, omega_ref, tau, *, keys=None, axis="isotropic",
                      gap=None, root=None):
    """Build an :class:`Imperfections` from a validated parameter file.

    Parameters
    ----------
    experiment : str or vacuum.experiments_io.Experiment
        A name under ``experiments/`` (loaded through
        :func:`vacuum.experiments_io.load_experiment`, which enforces the
        provenance rules and refuses incomplete files) or an already-loaded
        record.
    omega_ref : float
        Reference angular frequency (rad/s) fixing the lattice energy unit;
        the file's SI values are converted in ``vacuum.experiments_io`` and
        nowhere else.
    tau : float
        Interaction window in lattice time units (t * omega_ref).
    keys : mapping, optional
        Overrides for :data:`CIRCUIT_QED_KEYS`.
    gap : float, optional
        Detector gap in lattice units, overriding the file's gap quantity
        (harvesting sweeps scan the gap; the file fixes the device).
    root : path-like, optional
        Alternate experiments root.

    Notes
    -----
    Rates published as ordinary frequencies (MHz, GHz) are converted by the
    loader's energy rule, ``value * 2 pi / omega_ref`` — i.e. they are read
    as angular rates.  Papers are not always explicit about the 2 pi in a
    quoted "Gamma_1 = 8.7 MHz"; the convention used here is stated in the
    parameter files' notes, and a factor-2 pi ambiguity in a published rate
    is a provenance question for the source, never something to silently
    absorb in code.
    """
    exp = (
        experiment
        if hasattr(experiment, "quantities")
        else load_experiment(experiment, root=root)
    )
    kk = dict(CIRCUIT_QED_KEYS)
    if keys:
        kk.update(keys)
    lat = exp.lattice(float(omega_ref))
    missing = [v for k, v in kk.items() if k != "gap" and v not in lat]
    if missing:
        raise KeyError(
            f"experiment {exp.name!r} has no lattice-convertible quantity for "
            f"{missing} (available: {sorted(lat)})"
        )
    if gap is None:
        if kk["gap"] not in lat:
            raise KeyError(
                f"experiment {exp.name!r} has no gap quantity {kk['gap']!r}; "
                f"pass gap=... explicitly"
            )
        gap = lat[kk["gap"]]
    gap_val = float(np.mean(np.atleast_1d(np.asarray(gap, dtype=float))))
    return imperfections_from_rates(
        gaps=gap_val,
        tau=float(tau),
        T=float(np.max(np.atleast_1d(np.asarray(lat[kk["temperature"]], float)))),
        Gamma_1=float(np.max(np.atleast_1d(np.asarray(lat[kk["relaxation"]], float)))),
        Gamma_phi=float(
            np.max(np.atleast_1d(np.asarray(lat[kk["dephasing"]], float)))
        ),
        axis=axis,
        provenance=f"{exp.name} (source: {exp.source[:80]}...)",
    )
