"""Passivity audit: local symplectics never lower the ground state's energy.

The ground state of any Hamiltonian is passive — in fact completely passive —
so no unitary (here: no Gaussian unitary, i.e. symplectic transformation plus
displacement) can extract mean energy from it (W. Pusz and S. L. Woronowicz,
Commun. Math. Phys. 58, 273 (1978); A. Lenard, J. Stat. Phys. 19, 575 (1978)).
For a quadratic H = (1/2) R^T H_mat R with H_mat = diag(K, I) this is exact
finite-dimensional linear algebra: the ground-state covariance minimizes
<H> = (1/2) Tr(H_mat V) over all physical V, so V -> S V S^T with S symplectic
can only raise <H>.

The audit throws random *local* symplectic operations (exp(Omega_sub H_sub)
for random symmetric H_sub on random subsets of a few modes) at a state and
records the worst energy change. On the ground state every change must be
>= -tol (tol absorbs float64 roundoff only). On an *active* state — e.g. a
locally squeezed vacuum — an energy-lowering local operation exists (the
inverse squeeze), and the audit run with a sampler that finds it must report
the violation of ground-state-style passivity: an audit that can never fire
is untrustworthy.

Conventions per docs/API.md: hbar = 1, block ordering R = (x_1..x_N, p_1..p_N),
mode k -> quadrature rows (k, N+k).
"""

from __future__ import annotations

import numpy as np
from scipy.linalg import expm

from vacuum.core import Omega, evolve, ground_state_cov, mean_energy

from .result import AuditResult, AuditViolation

__all__ = [
    "passivity_audit",
    "default_local_symplectic_sampler",
    "embed_local_symplectic",
]


def embed_local_symplectic(S_sub, modes, N):
    """Embed a local symplectic on `modes` into the full 2N-dim identity.

    S_sub is (2k, 2k) in *local* block ordering (x's of the listed modes,
    then their p's, in the listed order); the embedding maps local mode j to
    global mode modes[j] (rows modes[j] and N + modes[j]).
    """
    modes = np.asarray(list(modes), dtype=int)
    k = modes.size
    S_sub = np.asarray(S_sub, dtype=float)
    if S_sub.shape != (2 * k, 2 * k):
        raise ValueError(f"S_sub shape {S_sub.shape} does not match {k} modes")
    if modes.size and (modes.min() < 0 or modes.max() >= N):
        raise IndexError(f"mode index out of range for N={N}: {modes}")
    idx = np.concatenate([modes, modes + N])
    S = np.eye(2 * N)
    S[np.ix_(idx, idx)] = S_sub
    return S


def default_local_symplectic_sampler(rng, N, max_modes=3, strength=1.0):
    """Random local symplectic: exp(Omega_sub H_sub) on a random small subset.

    Draws a subset of 1..max_modes modes uniformly, a random symmetric
    H_sub (Gaussian entries, scaled by `strength`) on their quadratures, and
    returns the (2N, 2N) embedding of S_sub = exp(Omega_sub H_sub) — the
    Gaussian unitary generated by the quadratic Hamiltonian (1/2) R^T H_sub R
    (Serafini, "Quantum Continuous Variables", 2017, Sec. 3.1). Covers local
    rotations, squeezers, and few-mode beamsplitter-like mixing.

    Parameters
    ----------
    rng : numpy.random.Generator
        Seeded generator (the audit passes its own).
    N : int
        Total number of modes.
    max_modes : int
        Largest subset size (default 3).
    strength : float
        Scale of the generator entries (order-1 gives order-e^1 squeezing).
    """
    k = int(rng.integers(1, min(max_modes, N) + 1))
    modes = rng.choice(N, size=k, replace=False)
    A = rng.normal(size=(2 * k, 2 * k))
    H_sub = 0.5 * strength * (A + A.T)
    S_sub = expm(Omega(k) @ H_sub)
    return embed_local_symplectic(S_sub, modes, N)


def passivity_audit(
    K,
    V=None,
    sampler=None,
    n_samples=200,
    rng=None,
    tol=1e-12,
    strict=True,
    symplectic_tol=1e-8,
):
    """Check that sampled local symplectic operations never lower <H>.

    For each sampled S the audit computes
    delta_E = mean_energy(S V S^T, K) - mean_energy(V, K) and demands
    delta_E >= -tol. On the ground state of K this is the Pusz-Woronowicz
    passivity statement restricted to Gaussian unitaries, and any violation
    beyond roundoff is an *event* (PLAN.md anomaly protocol). On an active
    state (squeezed, thermal-displaced, ...) a violation is correct physics:
    the audit reports it, which is how it proves it has teeth.

    Parameters
    ----------
    K : (N, N) ndarray
        Coupling matrix of H = (1/2)(p.p + x.K.x).
    V : (2N, 2N) ndarray, optional
        State to audit; defaults to the ground state of K.
    sampler : callable(rng, N) -> (2N, 2N) symplectic, optional
        Source of candidate operations; defaults to
        :func:`default_local_symplectic_sampler` (random local symplectics on
        random subsets of <= 3 modes). Every returned matrix is verified to be
        symplectic to `symplectic_tol` (a failure there is a sampler bug and
        raises ValueError, not an AuditViolation).
    n_samples : int
        Number of operations to draw.
    rng : numpy.random.Generator or int or None
        Seeded generator (an int seeds a fresh one; None uses seed 0).
    tol : float
        Roundoff allowance: the audit passes iff min(delta_E) >= -tol.
    strict : bool
        If True (default), raise :class:`AuditViolation` on failure; else
        return the failed result.

    Returns
    -------
    AuditResult
        ``worst_violation`` = max(0, -min(delta_E)) (nats-free energy units,
        hbar = 1). ``details`` holds ``delta_E`` (all samples), ``min_delta_E``,
        ``argmin``, ``E0``, and ``worst_S`` — the sampled operation achieving
        the worst energy change, so a violation is *exhibited*, not just
        counted.
    """
    K = np.asarray(K, dtype=float)
    N = K.shape[0]
    if V is None:
        V = ground_state_cov(K)
    V = np.asarray(V, dtype=float)
    if V.shape != (2 * N, 2 * N):
        raise ValueError(f"V shape {V.shape} incompatible with K shape {K.shape}")
    if sampler is None:
        sampler = default_local_symplectic_sampler
    if rng is None or isinstance(rng, (int, np.integer)):
        rng = np.random.default_rng(0 if rng is None else int(rng))

    Om = Omega(N)
    E0 = mean_energy(V, K)
    deltas = np.empty(n_samples)
    worst_S = None
    worst_idx = -1
    for i in range(n_samples):
        S = np.asarray(sampler(rng, N), dtype=float)
        defect = np.max(np.abs(S @ Om @ S.T - Om))
        if defect > symplectic_tol:
            raise ValueError(
                f"sampler returned a non-symplectic matrix on sample {i}: "
                f"max|S Omega S^T - Omega| = {defect:.3e} > {symplectic_tol:.1e}"
            )
        deltas[i] = mean_energy(evolve(V, S), K) - E0
        if worst_idx < 0 or deltas[i] < deltas[worst_idx]:
            worst_idx = i
            worst_S = S

    min_delta = float(np.min(deltas)) if n_samples else 0.0
    passed = min_delta >= -tol
    result = AuditResult(
        name="passivity",
        passed=passed,
        worst_violation=max(0.0, -min_delta),
        details={
            "delta_E": deltas,
            "min_delta_E": min_delta,
            "argmin": int(worst_idx),
            "worst_S": worst_S,
            "E0": E0,
            "n_samples": int(n_samples),
            "tol": float(tol),
        },
    )
    if strict and not passed:
        raise AuditViolation(result)
    return result
